#whatsapp:
#  access-token: EAAaGNxn2QDYBO2tZBWLwNMOpaZBZBViRXJktapeX1JTnelSMeX2cC3nyyA98Lh0ZBib9B64MMHiW25F4dx3RoDjimaF040YabSSrsZCvRfbakctjcDZBbmZBcRTPeKc0WbItU8SFh2nmUqzPjPohZCxNB1pp6ervm0sOhddc3xDZAStj6r9QAMFjQGlZBSTbb6Lbns7QPcQft279fS4YVZCUqdMI97eueFAZAlxBTX69MqZAYkJ8ZD
#  phone-number-id: 65eb5b0ca03818e9b59cb89d5eaea1d5
#  template-name: hello_world
#  language: en_US
#  recipient-phone: 7503279140
twilio:
  accountSid: AC90501208107f247724e90c72ff43994a
  authToken: 428cba6eaef61d62902229f5cf0267e6
  fromNumber: whatsapp:+15551517137