spring.application.name=Whtsapp-Message-POC
server.port=8097
#whatsapp.api-url=https://graph.facebook.com/v22.0/638958102643087/messages
#whatsapp.phone-id=638958102643087
#whatsapp.token=EAATSIOzlFv0BO50iiXk1aTXxfWOzNFXgqQWopmRVrEbG5cXKB95NNAZB7oCoZAaVHVUgDmtWYRFSvi5rIHtewiM3ny7v9cmcQPCQtdFEyyNcarZA4YpSH7cKm6crJLx4VPf6dZCxuIzts7YsOWbUWUgJxhQTFdcY4RDJ13ZALwAGyiYZAtQLyViWxPuOAUpJOAzRxmvVcgn7CPnVCWjZBGxATPAQyMREFF4IxHHCqhUNKuKyEkfRqiN5R8nhTv9
#whatsapp.language:en_US
#whatsapp.recipient-phone:917503279140